package schema

import (
	"fmt"
	"go/format"
	"slices"
	"strconv"
	"strings"
	"time"
	"unicode"
)

// structural names the keywords the emitter reads as shape; every other keyword is a constraint and
// rides the bbschema tag verbatim (rule D4).
var structural = map[string]bool{
	"type": true, "properties": true, "required": true, "items": true,
	"$ref": true, "$defs": true, "$schema": true, "$id": true, "$anchor": true, "$comment": true,
}

// EmitOptions carries what a generated model file needs beyond the document itself (rule D4).
type EmitOptions struct {
	// Package is the package clause the emitted file carries.
	Package string
	// Name is the Go type name the document's root object emits as.
	Name string
	// GeneratedAt stamps the header; the zero value stamps none, which is what makes the emitter
	// byte-deterministic for a test that needs it.
	GeneratedAt time.Time
}

// Emit renders Go struct models for one JSON Schema document — the inverse of Derive (rule D4).
func Emit(document map[string]any, opts EmitOptions) ([]byte, error) {
	if opts.Package == "" || opts.Name == "" {
		return nil, fmt.Errorf("bbsdk/schema: emitting a model needs a package clause and a root type name")
	}
	e := &emitter{defs: objectMember(document, "$defs"), emitted: map[string]bool{}}
	e.queue(opts.Name, document, "#")
	var source strings.Builder
	source.WriteString("// Code generated by bb schema gen; DO NOT EDIT.\n")
	if !opts.GeneratedAt.IsZero() {
		source.WriteString("// Generated at " + opts.GeneratedAt.UTC().Format(time.RFC3339) + ".\n")
	}
	source.WriteString("\npackage " + opts.Package + "\n")
	// The worklist grows as fields are rendered, so the loop reads it by index rather than ranging.
	for i := 0; i < len(e.pending); i++ {
		rendered, err := e.structType(e.pending[i])
		if err != nil {
			return nil, err
		}
		source.WriteString("\n" + rendered)
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("bbsdk/schema: the emitted model is not valid Go: %w", err)
	}
	return formatted, nil
}

// model is one struct the emitter owes: its Go name, its object schema and where it came from.
type model struct {
	name     string
	document map[string]any
	pointer  string
}

// emitter carries one emission's worklist and the $defs block its references resolve against.
type emitter struct {
	defs    map[string]any
	pending []model
	emitted map[string]bool
}

// queue files one struct to emit, skipping a name already owed.
func (e *emitter) queue(name string, document map[string]any, pointer string) {
	if e.emitted[name] {
		return
	}
	e.emitted[name] = true
	e.pending = append(e.pending, model{name: name, document: document, pointer: pointer})
}

// structType renders one struct: its required fields first in the document's own order, then its
// optional fields under sorted member names, so a re-emission is byte-identical (rule D4).
func (e *emitter) structType(m model) (string, error) {
	properties := objectMember(m.document, "properties")
	required := stringsOf(m.document["required"])
	var rendered strings.Builder
	fmt.Fprintf(&rendered, "// %s is one %s value.\ntype %s struct {\n", m.name, m.name, m.name)
	for _, member := range order(properties, required) {
		property, isObject := properties[member].(map[string]any)
		if !isObject {
			return "", fmt.Errorf("bbsdk/schema: the property %q at %q is not a schema object", member, m.pointer)
		}
		optional := !slices.Contains(required, member)
		where := m.pointer + "/properties/" + escapeToken(member)
		goType, err := e.goType(property, m.name+exported(member), where)
		if err != nil {
			return "", err
		}
		tag, err := fieldTag(member, property, optional, where)
		if err != nil {
			return "", err
		}
		if optional {
			goType = "*" + goType
		}
		fmt.Fprintf(&rendered, "\t%s %s %s\n", exported(member), goType, tag)
	}
	rendered.WriteString("}\n")
	return rendered.String(), nil
}

// goType maps one property schema onto the Go type Derive would map back (rule D4).
func (e *emitter) goType(property map[string]any, nestedName, where string) (string, error) {
	if reference, referenced := property["$ref"].(string); referenced {
		name, found := strings.CutPrefix(reference, defsPointer)
		if !found || name == "" {
			return "", fmt.Errorf("bbsdk/schema: the $ref %q at %q is not a same-document $defs reference", reference, where)
		}
		document, declared := e.defs[name].(map[string]any)
		if !declared {
			return "", fmt.Errorf("bbsdk/schema: the $ref %q at %q names nothing in $defs", reference, where)
		}
		e.queue(exported(name), document, "#/$defs/"+escapeToken(name))
		return exported(name), nil
	}
	declared, isText := property["type"].(string)
	if !isText {
		return "", fmt.Errorf("bbsdk/schema: the schema at %q declares no single type, which the emitter cannot express", where)
	}
	switch declared {
	case "string":
		return "string", nil
	case "integer":
		return "int64", nil
	case "number":
		return "float64", nil
	case "boolean":
		return "bool", nil
	case "array":
		items, isObject := property["items"].(map[string]any)
		if !isObject {
			return "", fmt.Errorf("bbsdk/schema: the array at %q declares no items schema", where)
		}
		element, err := e.goType(items, nestedName+"Item", where+"/items")
		if err != nil {
			return "", err
		}
		return "[]" + element, nil
	case "object":
		e.queue(nestedName, property, where)
		return nestedName, nil
	default:
		return "", fmt.Errorf("bbsdk/schema: the type %q at %q is outside the model subset", declared, where)
	}
}

// fieldTag renders one field's json tag and the bbschema tag carrying every constraint keyword the
// derive would re-emit; a value the tag grammar cannot carry is a named error, never a drop (rule D4).
func fieldTag(member string, property map[string]any, optional bool, where string) (string, error) {
	name := member
	if optional {
		name += ",omitempty"
	}
	keywords := make([]string, 0, len(property))
	for keyword := range property {
		if !structural[keyword] {
			keywords = append(keywords, keyword)
		}
	}
	slices.Sort(keywords)
	entries := make([]string, 0, len(keywords))
	for _, keyword := range keywords {
		value, err := tagValue(property[keyword], keyword, where)
		if err != nil {
			return "", err
		}
		entries = append(entries, keyword+"="+value)
	}
	tag := "`json:" + strconv.Quote(name)
	if len(entries) > 0 {
		tag += " " + constraintTag + ":" + strconv.Quote(strings.Join(entries, ","))
	}
	return tag + "`", nil
}

// tagValue renders one constraint keyword's value in the tag's own grammar.
func tagValue(value any, keyword, where string) (string, error) {
	if members, isList := value.([]any); isList {
		rendered := make([]string, 0, len(members))
		for _, member := range members {
			text, err := scalarText(member, keyword, where)
			if err != nil {
				return "", err
			}
			if strings.ContainsAny(text, "|") {
				return "", fmt.Errorf("bbsdk/schema: the %q member %q at %q carries the enum separator, which the tag cannot express", keyword, text, where)
			}
			rendered = append(rendered, text)
		}
		return strings.Join(rendered, "|"), nil
	}
	return scalarText(value, keyword, where)
}

// scalarText renders one constraint scalar, refusing what the tag grammar cannot carry.
func scalarText(value any, keyword, where string) (string, error) {
	var text string
	switch typed := value.(type) {
	case string:
		text = typed
	case bool:
		text = strconv.FormatBool(typed)
	case float64:
		text = strconv.FormatFloat(typed, 'f', -1, 64)
	default:
		return "", fmt.Errorf("bbsdk/schema: the %q value at %q is a %T, which the tag cannot express", keyword, where, value)
	}
	if strings.ContainsAny(text, ",") {
		return "", fmt.Errorf("bbsdk/schema: the %q value %q at %q carries the tag separator, which the tag cannot express", keyword, text, where)
	}
	return text, nil
}

// order lists a struct's members: the required ones in the document's own order, then the rest
// sorted, which is what makes the emitted source deterministic and the round trip exact (rule D4).
func order(properties map[string]any, required []string) []string {
	ordered := make([]string, 0, len(properties))
	for _, member := range required {
		if _, declared := properties[member]; declared {
			ordered = append(ordered, member)
		}
	}
	rest := make([]string, 0, len(properties))
	for member := range properties {
		if !slices.Contains(required, member) {
			rest = append(rest, member)
		}
	}
	slices.Sort(rest)
	return append(ordered, rest...)
}

// objectMember reads one object-valued member of a document, nil when it carries none.
func objectMember(document map[string]any, name string) map[string]any {
	member, isObject := document[name].(map[string]any)
	if !isObject {
		return nil
	}
	return member
}

// stringsOf reads a decoded JSON string list, ignoring what is not one.
func stringsOf(value any) []string {
	items, isList := value.([]any)
	if !isList {
		return nil
	}
	texts := make([]string, 0, len(items))
	for _, item := range items {
		if text, isText := item.(string); isText {
			texts = append(texts, text)
		}
	}
	return texts
}

// exported renders a member name as an exported Go identifier.
func exported(member string) string {
	var name strings.Builder
	upper := true
	for _, symbol := range member {
		switch {
		case unicode.IsLetter(symbol) || unicode.IsDigit(symbol):
			if upper {
				name.WriteRune(unicode.ToUpper(symbol))
				upper = false
				continue
			}
			name.WriteRune(symbol)
		default:
			upper = true
		}
	}
	rendered := name.String()
	if rendered == "" {
		return "Field"
	}
	if unicode.IsDigit(rune(rendered[0])) {
		return "F" + rendered
	}
	return rendered
}
