package schema

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"reflect"

	"github.com/Clifford-Foster/slate-sdk-go/manifest"
)

// generationMarker is the artifact's own statement of where its bytes came from (rule D2).
const generationMarker = "bb_sdk_go schema.WriteSchemas — generated by go generate; do not edit"

// Ref is a schema-dictionary reference, dict:<name>@<version>, written verbatim and never derived (rule D2).
type Ref string

// Expect is a read expectation: the required type plus the strict marker (rule D2).
type Expect struct {
	// Type is an instance of the type values on this pattern must satisfy, or a Ref.
	Type any
	// Strict opts the read into the board-side activation gate.
	Strict bool
}

// Declarations are the two declaration names a component's schemas.go carries (rule D2).
type Declarations struct {
	// WriteSchemas maps a writes pattern to an instance of that write's struct type, or a Ref.
	WriteSchemas map[string]any
	// ReadExpectations maps a reads pattern to the expectation values on it must satisfy.
	ReadExpectations map[string]Expect
}

// WriteSchemas derives every declared type, passes every Ref through, and writes schemas.gen.json at path (rule D2).
func WriteSchemas(path string, decl Declarations) error {
	writes := map[string]any{}
	for pattern, instance := range decl.WriteSchemas {
		document, err := declaredSource(instance)
		if err != nil {
			return fmt.Errorf("bbsdk/schema: the write schema declared for %q: %w", pattern, err)
		}
		writes[pattern] = document
	}
	reads := map[string]any{}
	for pattern, expect := range decl.ReadExpectations {
		document, err := declaredSource(expect.Type)
		if err != nil {
			return fmt.Errorf("bbsdk/schema: the read expectation declared for %q: %w", pattern, err)
		}
		reads[pattern] = map[string]any{"schema": document, "strict": expect.Strict}
	}
	artifact, err := artifactBytes(map[string]any{"read_expectations": reads, "write_schemas": writes})
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, artifact, 0o644); err != nil {
		return fmt.Errorf("bbsdk/schema: writing the artifact at %q: %w", path, err)
	}
	return nil
}

// declaredSource renders one declared value as its artifact source: a Ref verbatim once rule 33's
// grammar holds (resolution is the toolchain's alone), anything else derived (rule D2).
func declaredSource(declared any) (any, error) {
	reference, isRef := declared.(Ref)
	if !isRef {
		return deriveDeclared(declared)
	}
	if _, _, valid := manifest.DictionaryReference(string(reference)); !valid {
		return nil, fmt.Errorf("the Ref %q is not a dict:<name>@<version> dictionary reference (manifest.md rule 33)",
			string(reference))
	}
	return string(reference), nil
}

// deriveDeclared derives one declared type from the instance a Declarations value carries (rule D2).
func deriveDeclared(instance any) (map[string]any, error) {
	if instance == nil {
		return nil, &DeriveError{Construct: "nil"}
	}
	declared := reflect.TypeOf(instance)
	if declared.Kind() == reflect.Pointer {
		declared = declared.Elem()
	}
	return derive(declared)
}

// artifactBytes renders the artifact deterministically: the maps under sorted member names, the
// reserved _bb block pinned last, and its hash trailer taken over exactly the bytes that precede
// the splice — the rule-11a idiom, so regeneration is diff-clean and a hand edit is catchable
// without decoding and re-encoding the document (rule D2).
func artifactBytes(body map[string]any) ([]byte, error) {
	var encoded bytes.Buffer
	writer := json.NewEncoder(&encoded)
	writer.SetEscapeHTML(false)
	if err := writer.Encode(body); err != nil {
		return nil, fmt.Errorf("bbsdk/schema: encoding the artifact: %w", err)
	}
	prefix := bytes.TrimRight(encoded.Bytes(), "\n")
	digest := sha256.Sum256(prefix)
	trailer, err := json.Marshal(map[string]any{
		"generated_by": generationMarker,
		"sha256":       hex.EncodeToString(digest[:]),
	})
	if err != nil {
		return nil, fmt.Errorf("bbsdk/schema: encoding the artifact trailer: %w", err)
	}
	var artifact bytes.Buffer
	artifact.Write(prefix[:len(prefix)-1])
	if len(prefix) > 2 {
		artifact.WriteByte(',')
	}
	artifact.WriteString(`"_bb":`)
	artifact.Write(trailer)
	artifact.WriteString("}\n")
	return artifact.Bytes(), nil
}
